import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Task 3',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex space-x-20 mx-10">
          <Link href="/" className='hover:text-blue-200'>Home</Link>
          <Link href="/about" className='hover:text-blue-200'>About</Link>
          <Link href="/contact" className='hover:text-blue-200'>Contact</Link>
          <Link href="/signin" className='hover:text-blue-200'>Sign in</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
